require 'require_all'
require_all 'lib'

describe "Moving the player to an empty room" do
  before :all do
    CaveGenerator.always_generate_this_hardcoded_cave("
      e.........
      ..........
      ..........
      ..........
      ..........
      ..........
      ..........
      ..........
      ..........
      ..........")
    @game = HuntTheWumpus.new(10)

    @game.receive_command(:move_south)
  end

  it "awards 1 point for exploring a new, empty room" do
    @game.status.points.should == 1
  end
end
