require 'require_all'
require_all 'lib'

require 'pry'

describe HuntTheWumpus do
  CaveGenerator.always_generate_this_hardcoded_cave("
    e.........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........")
  game = HuntTheWumpus.new(10)

  game.receive_command(:move_south)

  it "moves the player to the new room" do
    game.status.map[1][0].should == :player
  end
  it "reveals the contents of the previous room" do
    game.status.map[0][0].should == :entrance
  end
end