require 'require_all'
require_all 'lib'

describe "Moving near a wumpus" do
  before :all do

    CaveGenerator.always_generate_this_hardcoded_cave("
      e.........
      ..........
      W.........
      ..........
      ..........
      ..........
      ..........
      ..........
      ..........
      ..........")
    @game = HuntTheWumpus.new(10)

    @game.receive_command(:move_south)
  end

  it "tells us there is a foul odor" #do
    #@game.status.messages.should include(:there_is_a_foul_odor)
  #end
end
